### ISSUE TITLE
Flagging synteny error

### ISSUE THREAD

**Issue by Botantisty** [jtlovell/GENESPACE#58] opened 2023-01-12 19:17 UTC
Hello,

Thanks for all your work on this package. I love the figures it can make. 

I am currently getting the same error as reported in issues #36, #48, and #55. 

Namely:

```
4. Flagging synteny for each pair of genomes ...
        # Chunk 1 / 3 (08:32:35 PM) ...
Error in rbindlist(mclapply(1:nrow(chnk), mc.cores = nCores, function(i) { :
  Item 1 of input is not a data.frame, data.table or list
In addition: Warning message:
In mclapply(1:nrow(chnk), mc.cores = nCores, function(i) { :
  scheduled core 1 encountered error in user code, all values of the job will be affected
```

Following your suggestion for issue #36 I reduced the number of cores to 1 and the error changes to:
```
4. Flagging synteny for each pair of genomes ...
        ...Helianthus v. Smallanthus:          155672 hits (46512 anchors) in 799 blocks (587 SVs)
        ...Helianthus v. Conyza:               71955 hits (17064 anchors) in 232 blocks (179 SVs)
        ...Smallanthus v. Conyza:              84931 hits (29006 anchors) in 300 blocks (234 SVs)
        ...Smallanthus v. Smallanthus:         239696 hits (131535 anchors) in 752 blocks (515 SVs)
        ...Smallanthus v. Mikania:             90267 hits (31720 anchors) in 586 blocks (436 SVs)
        ...Helianthus v. Mikania:              75258 hits (18443 anchors) in 426 blocks (309 SVs)
Error in if (median(hc$n) > 5) hc <- subset(hc, n > 1) :
  missing value where TRUE/FALSE needed
```

The human - chicken example data runs without error. 

I previously had version 0.9.4 work with this data (but I wanted to specific chromosome order in the riparian plots). 

I haven't changed the genome ids and there is only one orthofinder run in the working directory.

Any ideas about what else to try?  
  
Thanks for your help.

P.S.

As a side note, there is a typo in the instructions for the human - chicken example. 

The line:
` rawFiles <- download_exampleData(path = genomeRepo)`
 
should read:
` rawFiles <- download_exampleData(filepath = genomeRepo)`

Full run information:
```
runwd <- file.path("/mnt/sda1/01_Data/Ambrosia/GS_Test2")
gids <- c("Vitis","Mikania", "Helianthus", "Smallanthus", "Conyza")
ploids <- c(1, 2, 2, 4, 1)
MSCanX.path <- "/mnt/sda1/03_Tools/MCScanX" 
orthofinder.path <- "orthofinder"
gpar.t2 <- init_genespace(genomeIDs = gids, ploidy = ploids,  wd = runwd,   path2mcscanx = MSCanX.path, path2orthofinder = orthofinder.path, nCores=12)
gpar.t2 <- run_genespace(gsParam = gpar.t2)

Checking Working Directory ... PASS: `/mnt/sda1/01_Data/Ambrosia/GS_Test2`
Checking user-defined parameters ...
        Genome IDs & ploidy ...
                Vitis      : 1
                Mikania    : 2
                Helianthus : 2
                Smallanthus: 4
                Conyza     : 1
        Outgroup ... NONE
        n. parallel processes ... 12
        collinear block size ... 12
        collinear block search radius ... 5
        n gaps in collinear block ... 5
        synteny buffer size... 100
        only orthogroups hits as anchors ... TRUE
        n secondary hits ... 0
Checking annotation files (.bed and peptide .fa):
        Vitis      : 37420 / 37420 geneIDs exactly match (PASS)
        Mikania    : 41487 / 41487 geneIDs exactly match (PASS)
        Helianthus : 75390 / 75390 geneIDs exactly match (PASS)
        Smallanthus: 80604 / 80604 geneIDs exactly match (PASS)
        Conyza     : 46993 / 46993 geneIDs exactly match (PASS)
Checking dependencies ...
        Found valid path to OrthoFinder v2.54: `orthofinder`
        Found valid path to DIAMOND2 v2.015: `diamond`
        Found valid MCScanX_h executable: `/mnt/sda1/03_Tools/MCScanX/MCScanX_h`

############################
1. Running orthofinder (or parsing existing results)
        Checking for existing orthofinder results ...
        Copying files over to the temporary directory:
                /mnt/sda1/01_Data/Ambrosia/GS_Test2/tmp
        Running the following command in the shell: `orthofinder -f
                /mnt/sda1/01_Data/Ambrosia/GS_Test2/tmp -t 12 -a 1 -X -o
                /mnt/sda1/01_Data/Ambrosia/GS_Test2/orthofinder`.This can take a while.
                To check the progress, look in the `WorkingDirectory` in the output (-o)
                directory


        OrthoFinder version 2.5.4 Copyright (C) 2014 David Emms

        2023-01-12 09:23:48 : Starting OrthoFinder 2.5.4
        12 thread(s) for highly parallel tasks (BLAST searches etc.)
        1 thread(s) for OrthoFinder algorithm
Checking required programs are installed                                                                                                            [150/1883]
        ----------------------------------------
        Test can run "mcl -h" - ok
        Test can run "fastme -i /mnt/sda1/01_Data/Ambrosia/GS_Test2/orthofinder/Results_Jan12/WorkingDirectory/SimpleTest.phy -o /mnt/sda1/01_Data/Ambrosia/GS_Test2/o
rthofinder/Results_Jan12/WorkingDirectory/SimpleTest.tre" - ok

        Dividing up work for BLAST for parallel processing
        --------------------------------------------------
        2023-01-12 09:23:50 : Creating diamond database 1 of 5
        2023-01-12 09:23:51 : Creating diamond database 2 of 5
        2023-01-12 09:23:51 : Creating diamond database 3 of 5
        2023-01-12 09:23:51 : Creating diamond database 4 of 5
        2023-01-12 09:23:51 : Creating diamond database 5 of 5

        Running diamond all-versus-all
        ------------------------------
        Using 12 thread(s)
        2023-01-12 09:23:52 : This may take some time....
        2023-01-12 09:23:52 : Done 0 of 25
        2023-01-12 09:43:12 : Done 10 of 25
        2023-01-12 12:06:45 : Done all-versus-all sequence search

        Running OrthoFinder algorithm
        -----------------------------
        2023-01-12 12:06:46 : Initial processing of each species
        2023-01-12 12:07:27 : Initial processing of species 0 complete
        2023-01-12 12:08:30 : Initial processing of species 1 complete
        2023-01-12 12:09:02 : Initial processing of species 2 complete
        2023-01-12 12:10:00 : Initial processing of species 3 complete
        2023-01-12 12:10:29 : Initial processing of species 4 complete
        2023-01-12 12:10:48 : Connected putative homologues
        2023-01-12 12:10:52 : Written final scores for species 0 to graph file
        2023-01-12 12:10:59 : Written final scores for species 1 to graph file
        2023-01-12 12:11:03 : Written final scores for species 2 to graph file
        2023-01-12 12:11:10 : Written final scores for species 3 to graph file
        2023-01-12 12:11:13 : Written final scores for species 4 to graph file

        WARNING: program called by OrthoFinder produced output to stderr

        Command: mcl /mnt/sda1/01_Data/Ambrosia/GS_Test2/orthofinder/Results_Jan12/WorkingDirectory/OrthoFinder_graph.txt -I 1.5 -o /mnt/sda1/01_Data/Ambrosia/GS_Test
2/orthofinder/Results_Jan12/WorkingDirectory/clusters_OrthoFinder_I1.5.txt -te 1 -V all

        stdout
        ------
        b''
        stderr
        ------
        b'[mcl] cut <9> instances of overlap\n'
        2023-01-12 12:12:40 : Ran MCL

        Writing orthogroups to file
        ---------------------------
        OrthoFinder assigned 257661 genes (91.4% of total) to 30547 orthogroups. Fifty percent of all genes were in orthogroups with 10 or more genes (G50 was 10) and
 were contained in the largest 7084 orthogroups (O50 was 7084). There were 10390 orthogroups with all species present and 354 of these consisted entirely of single-co
py genes.

        2023-01-12 12:12:47 : Done orthogroups
        
         Analysing Orthogroups
        =====================

        Calculating gene distances
        --------------------------
        2023-01-12 12:16:39 : Done
        2023-01-12 12:16:41 : Done 0 of 22270
        2023-01-12 12:16:52 : Done 1000 of 22270
        2023-01-12 12:16:54 : Done 2000 of 22270
        2023-01-12 12:16:56 : Done 3000 of 22270
        2023-01-12 12:16:57 : Done 4000 of 22270
        2023-01-12 12:16:59 : Done 5000 of 22270
        2023-01-12 12:17:01 : Done 6000 of 22270
        2023-01-12 12:17:02 : Done 7000 of 22270
        2023-01-12 12:17:03 : Done 8000 of 22270
        2023-01-12 12:17:05 : Done 9000 of 22270
        2023-01-12 12:17:06 : Done 10000 of 22270
        2023-01-12 12:17:07 : Done 11000 of 22270
        2023-01-12 12:17:09 : Done 12000 of 22270
        2023-01-12 12:17:10 : Done 13000 of 22270
        2023-01-12 12:17:11 : Done 14000 of 22270
        2023-01-12 12:17:13 : Done 15000 of 22270
        2023-01-12 12:17:14 : Done 16000 of 22270
        2023-01-12 12:17:15 : Done 17000 of 22270
        2023-01-12 12:17:17 : Done 18000 of 22270
        2023-01-12 12:17:18 : Done 19000 of 22270
        2023-01-12 12:17:19 : Done 20000 of 22270
        2023-01-12 12:17:20 : Done 21000 of 22270
        2023-01-12 12:17:22 : Done 22000 of 22270

        Inferring gene and species trees
        --------------------------------

        10390 trees had all species present and will be used by STAG to infer the species tree

        Best outgroup(s) for species tree
        ---------------------------------
        2023-01-12 12:21:43 : Starting STRIDE
        2023-01-12 12:21:45 : Done STRIDE
        Observed 936 well-supported, non-terminal duplications. 929 support the best root and 7 contradict it.
        Best outgroup for species tree:
          Vitis

        Reconciling gene trees and species tree
        ---------------------------------------
        Outgroup: Vitis
        2023-01-12 12:21:45 : Starting Recon and orthologues
        2023-01-12 12:21:45 : Starting OF Orthologues
        2023-01-12 12:21:46 : Done 0 of 22270
        2023-01-12 12:21:58 : Done 1000 of 22270
        2023-01-12 12:22:02 : Done 2000 of 22270
        2023-01-12 12:22:06 : Done 3000 of 22270
        2023-01-12 12:22:09 : Done 4000 of 22270
        2023-01-12 12:22:12 : Done 5000 of 22270
        2023-01-12 12:22:15 : Done 6000 of 22270
        2023-01-12 12:22:17 : Done 7000 of 22270
        2023-01-12 12:22:20 : Done 8000 of 22270
        2023-01-12 12:22:22 : Done 9000 of 22270
        2023-01-12 12:22:24 : Done 10000 of 22270
        2023-01-12 12:22:26 : Done 11000 of 22270
        2023-01-12 12:22:28 : Done 12000 of 22270
        2023-01-12 12:22:30 : Done 13000 of 22270
        2023-01-12 12:22:32 : Done 14000 of 22270
        2023-01-12 12:22:33 : Done 15000 of 22270
        2023-01-12 12:22:35 : Done 16000 of 22270
        2023-01-12 12:22:37 : Done 17000 of 22270
        2023-01-12 12:22:38 : Done 18000 of 22270
        2023-01-12 12:22:39 : Done 19000 of 22270
        2023-01-12 12:22:41 : Done 20000 of 22270
        2023-01-12 12:22:42 : Done 21000 of 22270
        2023-01-12 12:22:43 : Done 22000 of 22270
        2023-01-12 12:22:43 : Done OF Orthologues

        Writing results files
        =====================
        2023-01-12 12:22:45 : Done orthologues

        Results:
            /mnt/sda1/01_Data/Ambrosia/GS_Test2/orthofinder/Results_Jan12/

        CITATION:
         When publishing work that uses OrthoFinder please cite:
         Emms D.M. & Kelly S. (2019), Genome Biology 20:238

         If you use the species tree in your work then please also cite:
         Emms D.M. & Kelly S. (2017), MBE 34(12): 3267-3278
         Emms D.M. & Kelly S. (2018), bioRxiv https://doi.org/10.1101/267914        re-ordering genomeIDs by the species tree: Vitis, Conyza, Smallanthus, Mikania,
                Helianthus

############################
2. Combining and annotating bed files w/ OGs and tandem array info ...
        ##############
        Flagging chrs. w/ < 10 unique orthogroups
        ...Conyza     : 0 genes on 0 small chrs.
        ...Helianthus : 0 genes on 0 small chrs.
        ...Mikania    : 0 genes on 0 small chrs.
        ...Smallanthus: 0 genes on 0 small chrs.
        ...Vitis      : 0 genes on 0 small chrs.
        ##############
        Flagging over-dispered OGs
        ...Conyza     : 17718 genes in 303 OGs hit > 8 unique places ***
        ...Helianthus : 13105 genes in 245 OGs hit > 16 unique places ***
        ...Mikania    :  5234 genes in 140 OGs hit > 16 unique places ***
        ...Smallanthus:  3858 genes in  40 OGs hit > 32 unique places
        ...Vitis      :  1061 genes in  40 OGs hit > 8 unique places
        NOTE! Genomes flagged *** have > 5% of genes in over-dispersed orthogroups. These
                are likely not great annotations and should be examined carefully
        ##############
        Annotation summaries (after exclusions):
        ...Conyza     : 29275 genes in 19693 OGs ||  7668 genes in  3174 arrays
        ...Helianthus : 62285 genes in 26097 OGs || 32797 genes in 10073 arrays
        ...Mikania    : 36253 genes in 20947 OGs || 11148 genes in  4437 arrays
        ...Smallanthus: 76746 genes in 34620 OGs || 10757 genes in  4155 arrays
        ...Vitis      : 36359 genes in 17619 OGs || 23942 genes in  6958 arrays

############################
3. Combining and annotating the blast files with orthogroup info ...
        # Chunk 1 / 2 (12:23:23 PM) ...
        ...Smallanthus v. Smallanthus: total hits = 1291856, same og = 367028
        ...Helianthus v. Helianthus:   total hits = 1434227, same og = 599771
        ...Helianthus v. Smallanthus:  total hits = 1712061, same og = 153700
        ...Smallanthus v. Conyza:      total hits = 1301466, same og = 77665
        ...Conyza v. Conyza:           total hits = 864287, same og = 423457
        ...Helianthus v. Conyza:       total hits = 1484181, same og = 85563
        ...Smallanthus v. Mikania:     total hits = 1152181, same og = 97782
        ...Helianthus v. Mikania:      total hits = 1299121, same og = 96287
        ...Smallanthus v. Vitis:       total hits = 1031705, same og = 68334
        ...Mikania v. Mikania:         total hits = 650720, same og = 201949
        ...Conyza v. Mikania:          total hits = 955020, same og = 57456
        ...Helianthus v. Vitis:        total hits = 1070964, same og = 70509
        # Chunk 2 / 2 (12:23:51 PM) ...
        ...Conyza v. Vitis:            total hits = 813903, same og = 35538
        ...Vitis v. Mikania:           total hits = 685453, same og = 38487
        ...Vitis v. Vitis:             total hits = 582980, same og = 186764

############################
4. Flagging synteny for each pair of genomes ...
        # Chunk 1 / 2 (12:24:02 PM) ...
Error in rbindlist(mclapply(1:nrow(chnk), mc.cores = nCores, function(i) { :
  Item 1 of input is not a data.frame, data.table or list
In addition: Warning message:
In mclapply(1:nrow(chnk), mc.cores = nCores, function(i) { :
  scheduled core 1 encountered error in user code, all values of the job will be affected 
```

**Comment by Jeremias-Brand** [comment] 2023-01-13 10:40
I am getting the same error as well. 

```
############################
4. Flagging synteny for each pair of genomes ...
        # Chunk 1 / 1 (11:31:49 AM) ...
Error in rbindlist(mclapply(1:nrow(chnk), mc.cores = nCores, function(i) { :
  Item 24 of input is not a data.frame, data.table or list
In addition: Warning message:
In mclapply(1:nrow(chnk), mc.cores = nCores, function(i) { :
  scheduled cores 24, 31, 33, 28, 27, 30, 29, 35, 34, 44, 36, 48, 60, 39, 41, 40, 61, 52, 46, 32, 42, 45, 47, 59, 53, 37, 49, 62, 51, 50, 43, 56, 63, 38, 65, 66, 54, 55, 58, 57, 64 encountered errors in user code, all values of the jobs will be affected
```
The orthofinder run seems complete and the `results` directory was populated as expected.

**Comment by jtlovell** [comment] 2023-01-13 18:30
Sorry about this all - 
Can you print the GENESPACE version you used? 

I'm at PAG for the next few days, so if this requires more than a little touch up to the code it will take me longer to turn around than normal. Appreciate the patience.
John

**Comment by Botantisty** [comment] 2023-01-13 19:29
Hey, the fact that you respond to issues quickly is awesome! 

devtools::session_info() reports
` GENESPACE            * 1.0.7     2022-12-29 [1] Github (jtlovell/GENESPACE@4f934dd)`



Here is the rest of the output in case it helps.
```
─ Session info ─────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.1.3 (2022-03-10)
 os       Ubuntu 20.04.5 LTS
 system   x86_64, linux-gnu
 ui       X11
 language en_CA:en
 collate  en_CA.UTF-8
 ctype    en_CA.UTF-8
 tz       America/Toronto
 date     2023-01-13
 pandoc   NA

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package              * version   date (UTC) lib source
 ade4                   1.7-20    2022-11-01 [2] CRAN (R 4.1.3)
 adegenet               2.1.8     2022-10-02 [2] CRAN (R 4.1.3)
 ape                  * 5.6-2     2022-03-02 [2] CRAN (R 4.1.3)
 apex                 * 1.0.4     2020-04-11 [2] CRAN (R 4.1.3)
 Biobase                2.54.0    2021-10-26 [1] Bioconductor
 BiocGenerics         * 0.40.0    2021-10-26 [2] Bioconductor
 BiocIO                 1.4.0     2021-10-26 [1] Bioconductor
 BiocParallel           1.28.3    2021-12-09 [2] Bioconductor
 Biostrings           * 2.62.0    2021-10-26 [2] Bioconductor
 bitops                 1.0-7     2021-04-24 [2] CRAN (R 4.1.3)
 cachem                 1.0.6     2021-08-19 [2] CRAN (R 4.1.3)
 callr                  3.7.3     2022-11-02 [2] CRAN (R 4.1.3)
 cli                    3.4.1     2022-09-23 [2] CRAN (R 4.1.3)
 cluster                2.1.4     2022-08-22 [2] CRAN (R 4.1.3)
 codetools              0.2-18    2020-11-04 [2] CRAN (R 4.1.0)
 colorspace             2.0-3     2022-02-21 [2] CRAN (R 4.1.3)
 crayon                 1.5.2     2022-09-29 [2] CRAN (R 4.1.3)
 data.table             1.14.6    2022-11-16 [2] CRAN (R 4.1.3)
 dbscan                 1.1-11    2022-10-27 [1] CRAN (R 4.1.3)
 DelayedArray           0.20.0    2021-10-26 [1] Bioconductor
 devtools               2.4.5     2022-10-11 [1] CRAN (R 4.1.3)
 digest                 0.6.31    2022-12-11 [2] CRAN (R 4.1.3)
 dplyr                  1.0.10    2022-09-01 [2] CRAN (R 4.1.3)
 ellipsis               0.3.2     2021-04-29 [2] CRAN (R 4.1.3)
 fansi                  1.0.3     2022-03-24 [2] CRAN (R 4.1.3)
 farver                 2.1.1     2022-07-06 [2] CRAN (R 4.1.3)
 fastmap                1.1.0     2021-01-25 [2] CRAN (R 4.1.3)
 fastmatch              1.1-3     2021-07-23 [2] CRAN (R 4.1.3)
 fs                     1.5.2     2021-12-08 [2] CRAN (R 4.1.3)
 generics               0.1.3     2022-07-05 [2] CRAN (R 4.1.3)
 GENESPACE            * 1.0.7     2022-12-29 [1] Github (jtlovell/GENESPACE@4f934dd)
 GenomeInfoDb         * 1.30.1    2022-01-30 [2] Bioconductor
 GenomeInfoDbData       1.2.7     2022-04-28 [2] Bioconductor
 GenomicAlignments      1.30.0    2021-10-26 [1] Bioconductor
 GenomicRanges        * 1.46.1    2021-11-18 [2] Bioconductor
 ggplot2                3.4.0     2022-11-04 [2] CRAN (R 4.1.3)
 glue                   1.6.2     2022-02-24 [2] CRAN (R 4.1.3)
 gtable                 0.3.1     2022-09-01 [2] CRAN (R 4.1.3)
 htmltools              0.5.4     2022-12-07 [2] CRAN (R 4.1.3)
 htmlwidgets            1.6.0     2022-12-15 [2] CRAN (R 4.1.3)
 httpuv                 1.6.7     2022-12-14 [2] CRAN (R 4.1.3)
 igraph                 1.3.5     2022-09-22 [2] CRAN (R 4.1.3)
 IRanges              * 2.28.0    2021-10-26 [2] Bioconductor
 labeling               0.4.2     2020-10-20 [2] CRAN (R 4.1.3)
 later                  1.3.0     2021-08-18 [2] CRAN (R 4.1.3)
 lattice                0.20-45   2021-09-22 [2] CRAN (R 4.1.1)
 lifecycle              1.0.3     2022-10-07 [2] CRAN (R 4.1.3)
 magrittr               2.0.3     2022-03-30 [2] CRAN (R 4.1.3)
 MASS                   7.3-58.1  2022-08-03 [2] CRAN (R 4.1.3)
 Matrix                 1.5-3     2022-11-11 [2] CRAN (R 4.1.3)
 MatrixGenerics         1.6.0     2021-10-26 [1] Bioconductor
 matrixStats            0.63.0    2022-11-18 [2] CRAN (R 4.1.3)
 memoise                2.0.1     2021-11-26 [2] CRAN (R 4.1.3)
 mgcv                   1.8-41    2022-10-21 [2] CRAN (R 4.1.3)
 mime                   0.12      2021-09-28 [2] CRAN (R 4.1.3)
 miniUI                 0.1.1.1   2018-05-18 [2] CRAN (R 4.1.3)
 msa                  * 1.26.0    2021-10-26 [2] Bioconductor
 munsell                0.5.0     2018-06-12 [2] CRAN (R 4.1.3)
 nlme                   3.1-161   2022-12-15 [2] CRAN (R 4.1.3)
 permute                0.9-7     2022-01-27 [2] CRAN (R 4.1.3)
 phangorn             * 2.10.0    2022-09-18 [2] CRAN (R 4.1.3)
 pillar                 1.8.1     2022-08-19 [2] CRAN (R 4.1.3)
 pkgbuild               1.4.0     2022-11-27 [2] CRAN (R 4.1.3)
 pkgconfig              2.0.3     2019-09-22 [2] CRAN (R 4.1.3)
 pkgload                1.3.2     2022-11-16 [2] CRAN (R 4.1.3)
 plyr                 * 1.8.8     2022-11-11 [2] CRAN (R 4.1.3)
 prettyunits            1.1.1     2020-01-24 [2] CRAN (R 4.1.3)
 processx               3.8.0     2022-10-26 [2] CRAN (R 4.1.3)
 profvis                0.3.7     2020-11-02 [2] CRAN (R 4.1.3)
 promises               1.2.0.1   2021-02-11 [2] CRAN (R 4.1.3)
 ps                     1.7.2     2022-10-26 [2] CRAN (R 4.1.3)
 purrr                  0.3.5     2022-10-06 [2] CRAN (R 4.1.3)
 quadprog               1.5-8     2019-11-20 [2] CRAN (R 4.1.3)
 R.methodsS3            1.8.2     2022-06-13 [2] CRAN (R 4.1.3)
 R.oo                   1.25.0    2022-06-12 [2] CRAN (R 4.1.3)
 R.utils                2.12.2    2022-11-11 [2] CRAN (R 4.1.3)
 R6                     2.5.1     2021-08-19 [2] CRAN (R 4.1.3)
 Rcpp                   1.0.9     2022-07-08 [2] CRAN (R 4.1.3)
 RCurl                  1.98-1.9  2022-10-03 [2] CRAN (R 4.1.3)
 remotes                2.4.2     2021-11-30 [2] CRAN (R 4.1.3)
 reshape2               1.4.4     2020-04-09 [2] CRAN (R 4.1.3)
 restfulr               0.0.15    2022-06-16 [1] CRAN (R 4.1.3)
 rjson                  0.2.21    2022-01-09 [2] CRAN (R 4.1.3)
 rlang                  1.0.6     2022-09-24 [2] CRAN (R 4.1.3)
 Rsamtools            * 2.10.0    2021-10-26 [2] Bioconductor
 rtracklayer            1.54.0    2021-10-26 [1] Bioconductor
 S4Vectors            * 0.32.4    2022-03-24 [2] Bioconductor
 scales                 1.2.1     2022-08-20 [2] CRAN (R 4.1.3)
 seqinr               * 4.2-23    2022-11-28 [2] CRAN (R 4.1.3)
 sessioninfo            1.2.2     2021-12-06 [2] CRAN (R 4.1.3)
 shiny                  1.7.4     2022-12-15 [2] CRAN (R 4.1.3)
 stringi                1.7.8     2022-07-11 [2] CRAN (R 4.1.3)
 stringr                1.5.0     2022-12-02 [2] CRAN (R 4.1.3)
 SummarizedExperiment   1.24.0    2021-10-26 [1] Bioconductor
 tibble                 3.1.8     2022-07-22 [2] CRAN (R 4.1.3)
 tidyselect             1.2.0     2022-10-10 [2] CRAN (R 4.1.3)
 urlchecker             1.0.1     2021-11-30 [2] CRAN (R 4.1.3)
 usethis                2.1.6     2022-05-25 [2] CRAN (R 4.1.3)
 utf8                   1.2.2     2021-07-24 [2] CRAN (R 4.1.3)
 vctrs                  0.5.1     2022-11-16 [2] CRAN (R 4.1.3)
 vegan                  2.6-4     2022-10-11 [2] CRAN (R 4.1.3)
 viridisLite            0.4.1     2022-08-22 [2] CRAN (R 4.1.3)
 withr                  2.5.0     2022-03-03 [2] CRAN (R 4.1.3)
 XML                    3.99-0.13 2022-12-04 [2] CRAN (R 4.1.3)
 xtable                 1.8-4     2019-04-21 [2] CRAN (R 4.1.3)
 XVector              * 0.34.0    2021-10-26 [2] Bioconductor
 yaml                   2.3.6     2022-10-18 [2] CRAN (R 4.1.3)
zlibbioc               1.40.0    2021-10-26 [2] Bioconductor
```

**Comment by jtlovell** [comment] 2023-01-13 21:07
Ugh. I'll have v1.0.8 pushed ASAP ... hopefully tomorrow. The whole point of this next update is to error out informatively from `synteny`.  I'll post here when its up. Hopefully it will be fully stable.

**Comment by jtlovell** [comment] 2023-01-19 16:09
Sorry about the delay here. I have it fixed, but need to check all downstream functions before pushing an update (it works for me now). I'll try to have it up by COB today, and will definitely have v1.0.8 at /dev by tomorrow 5pm PT. If you want it faster, post here that you can test it and I will push the update and we can make sure it is stable.

**Comment by Botantisty** [comment] 2023-01-19 16:37
I can be patient, if you'd rather wait. ;) However, I can make time to test it tomorrow if that would help.

**Comment by jtlovell** [comment] 2023-01-19 16:40
Thanks! Appreciate the patience. 
Let's plan on it being up tomorrow at this time and you can give it a go. I'll post here when its up. 

To make the errors informative, I had to separate out a few synteny steps into discrete parallelized steps. This required enough new code that I want to make sure I didn't botch anything. 

More soon. 
John

**Comment by jtlovell** [comment] 2023-01-19 20:31
ok v1.0.8 is up. If you are working with haploid genomes or a simple synteny map, then it should be good to go. If you are working with polyploids or really complex syntenic maps (segmental dups etc.), then know that I am still writing a major update to `plot_riparian` and `pangenome` that handle multi-mapping better. those updates will be reflected in v1.0.9, which will be posted in the next week or two.

**Comment by jtlovell** [comment] 2023-01-19 20:34
ah, you are working in sunflowers. I think that qualifies as very complex synteny. 
Look carefully at the dotplots and make sure they mesh with your riparian synteny map. 

Regardless, best to wait the week or two until the next version with a stable riparian plot before making results that you'll want to publish.

**Comment by Botantisty** [comment] 2023-01-20 14:46
Somedays I do think that I should be working with haploids instead. 😂 Thanks for letting me know.

**Comment by jtlovell** [comment] 2023-01-20 20:39
I just mean haploid representations of diploid (or higher ploidy) ... humans are biologically diploid (for the most part), but the genome is haploid (for the most part).

**Comment by jtlovell** [comment] 2023-01-23 19:23
I'm gonna close this, since I think the issue is fixed. If the same issue comes up, re open.

**Closed by jtlovell** 2023-01-23 19:23 UTC

**Comment by jtlovell** [comment] 2023-02-21 17:57
FYI. GENESPACE v1.1.3 is at /dev. Thanks for the help here. 
I'd like to see how this version handles this issue.
