### ISSUE TITLE
Error: subscript contains out-of-bounds indices

### ISSUE THREAD

**Issue by YanWangTF** [jtlovell/GENESPACE#90] opened 2023-05-02 18:56 UTC
I was using the latest version to compare two partial genomes. When it comes to checking annotation files, it reported the "Error: subscript contains out-of-bounds indices". I post it here in case this is a common issue. The output is also pasted below. Thank you.

Checking user-defined parameters ...
	Genome IDs & ploidy ... 
		genomeA: 1
		genomeB: 1
	Outgroup ... NONE
	n. parallel processes ... 16
	collinear block size ... 5
	collinear block search radius ... 25
	n gaps in collinear block ... 5
	synteny buffer size... 100
	only orthogroups hits as anchors ... TRUE
	n secondary hits ... 0
Checking annotation files (.bed and peptide .fa):
Error: subscript contains out-of-bounds indices

**Comment by jtlovell** [comment] 2023-05-03 00:41
This is an un-informative error that I want to fix. Can you print the output from `parse_annotations(..., troubleshoot = T)`. Or, alternatively, if you did not use that to format your annotations, the head of the files in `/peptide` and `/bed` directories?

**Comment by YanWangTF** [comment] 2023-05-03 01:35
I did not use the parse_annotation function. The head of the files in /peptide and /bed directories looks like this:
```shell
==> bed/genomeA.bed <==
1	1758473	1759406	G1599
1	1760584	1761480	G1600
1	1762168	1763734	G1601
1	1765351	1766566	G1602
1	1768850	1769531	G1603
1	1769996	1770810	G1604
1	1771574	1772695	G1605
1	1773116	1773863	G1606
1	1774347	1775403	G1607
==> bed/genomeB.bed <==
1	40390	40835	G6134
1	42236	43024	G6135
1	43071	43806	G6136
1	44258	45584	G6137
1	47149	48358	G6138
1	48780	52275	G6139
1	59249	61508	G6140
1	62732	64811	G6141
1	66329	67216	G6142
==> peptide/genomeA.fa <==
>G1599
MNDMNGFVWNDCPYITFWNHNKKESQKLKVGIETKVLLDGIVVKKSRFDPVFFQDDKINITVKLDRWGKGREYLPLQDMVGHFTKKCKNYGTTRIFDHTF
YGEINCQLAGGADQIHIGSKPGIFTTQKNDKVVATAPSFDGVCSVKAVVINIKVYQSNIKLKANFTKTKSSFASGVVEYIVDRIFPAKLPLIFLSKNPKV
KLAYISATRVFYNLAKGILDTDTDTDTDQD
>G1600
MSATYSYNANDKAGSDSKPVDNKAGDLTTAGAQKDSEANKGMNLTSAPVPLDDFEANDPELAQLKKQMMEMEQEAAKLRELQAQTTKAITEEHAKEDVDA
RSVYVGNVDYSSTPEELQAHFQSCGAINRVTILCDKYTGHPKGFAYVEFADKSSIQSALQFEGSLLHGRAIKVIQKRTNVPGYSGRGRGGRGGGPGYHFG
GGRGGGYYAPRGGRPYGRGRGRGRGAYFAPY
>G1601
MTVEGDIPRLGLTSEEFRQKGKEIIDFIADYYDNLNQVQPLSQVKPNFLYDLLPKEAPEEPESFDQVMADFNSKIMPGITHWQSGNFYGYYPANSTYPGI

==> peptide/genomeB.fa <==
>G6134
MRPSVYTASISLIVANLLSPIVGASTSAGTGNVNCSDSISQIEIAQGSDDSSVINYNWDSAIDVSCPSQDYLVTFDVDQTSDIYFAISTQKSLLTGEEVI
EGVIGVNTGSWLVVQVLELGW
>G6135
MRAAANTAKINNGTGMKKTTRKKKVVKTEDGLLEIDLGISSLQELCVRVIEKHIKDVTSFGDISSDAMNKVYGGGLLRFYDSAGGKRIKRVFTGSFGFWW
SLRSYDNTLISILIHSNSTIFESTLCNQILATNGLSAFSGTFLFSTDEDNNSSKDKNSTGTNSSQLKTPPIVTLPTCKNLHTPNLSFVRSTDHSAIPTLF
SNSPSLSTMFMNRKPESHPTNFFLV
>G6136
MKRNRVFGPRSALTSFLKEQGITNESIRERFQANNDVLEEGDEGQNEEIQQIQESNNESEREEDQEQNVIESGETSGEEDVEESSIGKRVTRSSNSKSKN
KKIKIDLKGSKSKGKDYESDVEGNKRKKRLGIESSNRDNEGLNASSARKGGRVEYCSMCKAKFLVREELMNDNGKRRILCLTCDKYMKNMNKRNKITS
```

**Comment by jtlovell** [comment] 2023-05-03 01:40
those look just fine ... would you mind sending me the files so I can troubleshoot? jlovell[at]hudsonalpha[dot]org

**Comment by YanWangTF** [comment] 2023-05-03 02:14
Files sent. Thank you for helping.

**Comment by jtlovell** [comment] 2023-05-03 13:38
Well, this is an easy fix - I had it hard coded that if you provided a genome with < 100 genes, it would error out. Now it returns an informative error. Here:

```
Checking annotation files (.bed and peptide .fa):
	genomeA: 9 / 9 geneIDs exactly match (PASS)
		WARNING! < 100 genes is too few for orthofinder
	genomeB: 9 / 9 geneIDs exactly match (PASS)
		WARNING! < 100 genes is too few for orthofinder
```

I have a couple other things to work on before pushing v1.2.4, but this warning will be included. In the meantime, try the run with a full genome worth of sequences (GENESPACE and OrthoFinder are not meant to be run on specific regions a priori).

**Comment by YanWangTF** [comment] 2023-05-03 16:08
That makes sense. Thank you, John.

**Closed** 2023-05-03 18:09 UTC

**Comment by yanarizzieri** [comment] 2024-12-03 20:00
Hello John,

I have been receiving  the same error but on a different situation. When trying to parse my files, the /bed and /peptide folders are not created and I receive 'Error: subscript contains out-of-bounds indices'

<img width="339" alt="Screenshot 2024-12-03 at 2 40 06 PM" src="https://github.com/user-attachments/assets/8f2ee90f-7aa1-4417-9f9c-305e0c8a375f">

Since the example data is working, I've crossed out an installation problem and assumed it was a problem with my file formating. But after comparing my file formats with the example data, I failed to find where the problem is.

This is how my gff3 files looks like:
SG1:
<img width="822" alt="Screenshot 2024-12-03 at 2 52 18 PM" src="https://github.com/user-attachments/assets/277e61cc-d77f-417c-9ef2-2c0f8255b278">


SG2:
<img width="821" alt="Screenshot 2024-12-03 at 2 53 01 PM" src="https://github.com/user-attachments/assets/51d3ddc0-55fe-48c3-a644-4579fe1f5d44">

This is how my fasta file headers looks like:
SG1:
<img width="433" alt="Screenshot 2024-12-03 at 2 51 38 PM" src="https://github.com/user-attachments/assets/eb583d8f-9075-448c-ac45-9062f30715a6">


SG2:
<img width="429" alt="Screenshot 2024-12-03 at 2 52 45 PM" src="https://github.com/user-attachments/assets/5b2db290-1434-4080-a23e-93713db32d27">


############################################################################################
In addition, I have created my on peptide and bed files for both genomes previously, but when trying to run 'gpar', it fails to identify gene ID's: 
<img width="489" alt="Screenshot 2024-12-03 at 2 45 12 PM" src="https://github.com/user-attachments/assets/0ac66306-050d-4741-9fed-f68613e3c4eb">

Weirdly, from this trial, it claims 36131 and 43298 gene IDs for each genome, but I have no clue where that number is coming from.

This is how my bed files look like:
SG1:
<img width="391" alt="Screenshot 2024-12-03 at 2 50 47 PM" src="https://github.com/user-attachments/assets/245ff25f-02e1-49f6-b2f4-c8c1cccd0d88">


SG2:
<img width="242" alt="Screenshot 2024-12-03 at 2 49 25 PM" src="https://github.com/user-attachments/assets/28794611-93f7-4c62-8822-e1a453e2e6b4">


This how my prot files look like:
SG1:
<img width="502" alt="Screenshot 2024-12-03 at 2 50 59 PM" src="https://github.com/user-attachments/assets/164ce310-1937-487e-8abb-0c375d3a8280">


SG2:
<img width="496" alt="Screenshot 2024-12-03 at 2 49 44 PM" src="https://github.com/user-attachments/assets/a1921179-f770-419c-ac30-4e28e898c0f4">




Any suggestions?

Ps: As I was writing this issue, I realized that because of the " gene=g#" info in the protein file header GENESPACE was not recognizing any matches on the bed files. Anyways, the first section of the issue about the parsing situation is still not working and I was wondering if there could be a way to ignore things after a space on the protein header (for the self parseners). SORRY FOR SUCH A LONG POST!!!

Thank you so much,

Y

**Comment by jtlovell** [comment] 2024-12-03 20:59
I'm not following ... your fasta headers are just chromosomes and DNA sequences? There is no situation that you should be providing GENESPACE with DNA.
