### ISSUE TITLE
Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by aberaslop** [jtlovell/GENESPACE#9] opened 2022-03-22 10:24 UTC
Hi!
Thank you so much for this nice program!
I have been trying to run it, and while I found a few hiccups in parsing the gff files, I think I managed to do it. I also had a previous orthofinder run obtained prior to genespace, so I recycled that data. I am running R from a Debian system. 

When I run the synteny step, though, I find this message:

gpar<-synteny(gsParam=gpar, blkSize= 20)
Synteny Parameters have not been set! Setting to defaults
Indexing location of orthofinder results ... Done!
Parsing the gff files ... 
	Reading the gffs and adding orthofinder IDs ... Done!
	Found 54365 global OGs for 54365 genes
	QC-ing genome to ensure chromosomes/scaffolds are big enough...
      		Genome: n. chrs PASS/FAIL, n. genes PASS/FAIL, n. OGs PASS/FAIL
		SPA: 9/0, 6765/0, 6765/0
		SPB: 8/0, 6453/0, 6453/0
		SPC: 13/1, 6814/1, 6814/1
		SPD: 20/2, 6839/2, 6839/2
		SPE: 21/0, 6947/0, 6947/0
		SPF: 10/2, 6925/2, 6925/2
		SPG: 12/1, 6709/1, 6709/1
		SPH: 13/8, 6889/18, 6889/18
	All look good!
	Defining collinear orthogroup arrays ... 
	Found the following counts of arrays / genome:
Pulling synteny for 36 unique pairwise combinations of genomes
	Running 1 chunks of up to 40 combinations each:
	Chunk 1 / 1 (06:17:14 AM) ... Done!
Error: $ operator is invalid for atomic vectors
In addition: Warning message:
In mclapply(1:nrow(splSynp[[i]]), mc.cores = nCores, function(j) { :
  all scheduled cores encountered errors in user code

Any suggestion of what might be going on is greatly appreciated!

Thanks again!

L.

**Comment by jtlovell** [comment] 2022-03-22 17:08
Thank you for using GENESPACE!
This is a particularly tricky spot to troubleshoot, but I'm sure we can figure it out.
Can you re run as follows (and re-post the error here, or email it)? It will produce a more informative error. If the issue is not obvious, we may need to work it out iteratively via email - feel free to write me directly at jlovell@hudsonalpha.org
John

```
gpar$params$nCores <- 1
gpar<-synteny(gsParam=gpar, blkSize= 20)
```

**Comment by jtlovell** [comment] 2022-03-22 18:08
Closing this for now - will post a bug fix or explanation once we nail down the issue.

**Comment by jtlovell** [comment] 2022-03-23 15:37
To close this out, the issue was that the files had been re-named. GENESPACE couldn't find an exact match to the blast hits and failed. In the next release, I will make sure there is a check that the files are there and a more informative error will be returned if not.

**Closed by jtlovell** 2022-03-23 15:37 UTC

**Comment by dabitz** [comment] 2023-02-15 16:49
OK. I am getting a similar message, but don't know what's wrong...
After running orthofinder I go this:

Warning message:
In system2(gsParam$paths$diamondCall, pwp$com[i], stdout = TRUE,  :
  running command ''diamond' blastp  --quiet -e 0.1 -p 40 --compress 1 -d Cyperids/orthofinder/diamondDBSpecies7.dmnd -q Cyperids/orthofinder/Species7.fa -o Cyperids/orthofinder/Blast7_7.txt.gz 2>&1' had status 132


After running this:
gpar$params$nCores <- 1
gpar<-synteny(gsParam=gpar, blkSize= 20)

I got this:
Error in strsplit(bl$ofID1[1], "_") : non-character argument
In addition: Warning message:
In fread(blFile, showProgress = FALSE, verbose = FALSE, select = c(1,  :
  File 'Cyperids/orthofinder/Blast7_7.txt.gz' has size 0. Returning a NULL data.table.

Any idea?
thanks!
Andre

**Comment by jtlovell** [comment] 2023-02-15 16:53
this looks like either (a) you have given orthofinder DNA and not peptide fastas, or (b) you have an old version of diamond2 or orthofinder. Orthofinder has to be >= 2.5.4 and Diamond >= v2.0.14.

**Comment by dabitz** [comment] 2023-02-15 17:03
nor (a) or (b) though :(

**Comment by jtlovell** [comment] 2023-02-15 17:08
Well, there is something wrong with genome7 ... not sure what. This is an orthofinder/diamond problem that cannot be diagnosed by genespace v0.9. 
Your best bet is to wait until v1.1.3 is posted to /dev. This should be next week, but might be tomorrow if I get my act together. Theres about 800 lines of code in v1 to check and Andre-proof the input files.

**Comment by dabitz** [comment] 2023-02-15 17:11
Thanks! I will check in detail the genome 7, I guess this is the order of set with gids <- right?

**Comment by jtlovell** [comment] 2023-02-15 17:12
good guess. no, it is alphabetical order. Look in the /orthofinder directory. There is a file SpeciesIDs.txt that gives the dictionary.

**Comment by dabitz** [comment] 2023-02-15 17:13
great! Thanks man! Love your work ;-)
